# Package: Gate Garage Guard
# Version: 1.0.5 Beta
#
# Description:
#   A "Nervous System" for a dumb 433MHz gate relay. This package sits between your
#   dashboard and the hardware, ensuring the gate only moves when it makes sense.
#
# Why This Exists:
#   Radio relays are deaf and blind; they just click. The logic in this package checks
#   if the gate is already open before opening it, monitors vibration to distinguish
#   wind from intruders, and retries commands if the gate gets stuck.
#
# The Hardware (The Senses):
#   1. binary_sensor.door_gate_garage_contact: The "Eye." It tells the brain if the
#      gate is actually open or closed, preventing the relay from firing blindly.
#   2. binary_sensor.vibration_gate_garage_vibration: The "Raw Nerve." It feels
#      every rattle, which the software then filters to ignore wind or casual bumps.
#
# Entities Created (Add these to your Dashboard):
#   1. cover.gate_garage_package_guarded (The General): Use this entity for all control.
#      It safely manages the actual relay and handles the retry logic.
#   2. input_text.gate_garage_package_status_message (The Town Crier): Displays real-time
#      status like "Processing Open...", "Retry: Closing...", or "Success".
#   3. sensor.gate_garage_package_error_display (The Warning Light): The single source of
#      truth for trouble. Shows "None" or specific errors like "Error: Close Failed".
#   4. binary_sensor.gate_garage_package_vibration_smart (The Filter): A calculated sensor
#      that only trips on sustained vibration or rapid double-taps.
#
# Search Tips:
#   - Search "gate_garage" to see EVERYTHING (Hardware + Package Logic).
#   - Search "gate_garage_package" to see ONLY the Logic Layer.

# Changelog:
#   v1.0.5: Fixed 'wait is undefined' error in Smart Vibration sensor by using timestamp math
#           instead of automation-specific logic. Added explicit triggers to Error Display 
#           sensor to prevent 'unknown' state on boot.
#   v1.0.4: Renamed all package entities to 'gate_garage_package_*' convention for
#           improved search filtering.
#   v1.0.3: Added documentation regarding 15s timeout based on ~12s gate travel time.
#   v1.0.2: Integrated sensor.restarting_status to block operations during boot.
#   v1.0.1: Changed invalid 'unknown' state return to 'none'. Enhanced availability
#           check. Fixed 'unavailable' vibration sensor.
#   v1.0.0: Initial Release.

# ------------------------------------------------------------------------------
# 1. INPUTS (Memory Banks)
# ------------------------------------------------------------------------------
input_text:
  gate_garage_package_status_message:
    name: Gate Garage Package Status Message
    icon: mdi:message-text-clock
    initial: "System Ready"
    # Used for transient messages: "Processing...", "Closing...", "Open"

  gate_garage_package_error_latch:
    name: Gate Garage Package Error Memory
    icon: mdi:alert-circle
    initial: "None"
    # Stores logic failures (e.g., "Close Failed"). Reset on successful new command.

# ------------------------------------------------------------------------------
# 2. TEMPLATES (The Nervous System & The Face)
# ------------------------------------------------------------------------------
template:
  # --- The Error Display Entity ---
  # This is the single entity to use on your dashboard for error reporting.
  # Added triggers to ensure state is calculated immediately on change or start.
  - trigger:
      - trigger: state
        entity_id: switch.stove_vent_relays_gate
      - trigger: state
        entity_id: binary_sensor.door_gate_garage_contact
      - trigger: state
        entity_id: input_text.gate_garage_package_error_latch
      - trigger: homeassistant
        event: start
    sensor:
      - name: "Gate Garage Package Error Display"
        unique_id: sensor_gate_garage_package_error_display
        icon: mdi:alert-box
        state: >-
          {% set switch_status = states('switch.stove_vent_relays_gate') %}
          {% set contact_status = states('binary_sensor.door_gate_garage_contact') %}
          {# We default to 'None' if the input_text is not yet ready #}
          {% set logic_error = states('input_text.gate_garage_package_error_latch') | default('None', true) %}
          {% set logic_error = 'None' if logic_error in ['unknown', 'unavailable'] else logic_error %}
          
          {% if switch_status in ['unavailable', 'unknown'] %}
            Switch Unavailable
          {% elif contact_status in ['unavailable', 'unknown'] %}
            Sensor Unavailable
          {% else %}
            {{ logic_error }}
          {% endif %}

  # --- Vibration Filters ---
  - binary_sensor:
      - name: "Gate Garage Package Vibration Guarded"
        unique_id: binary_sensor_gate_garage_package_vibration_guarded
        device_class: vibration
        # True if raw sensor is on for > 5 seconds
        state: >-
          {{ is_state('binary_sensor.vibration_gate_garage_vibration', 'on') }}
        delay_on: 5

  - trigger:
      - trigger: state
        entity_id: binary_sensor.vibration_gate_garage_vibration
        to: "on"
      # Wake up the sensor on boot so it isn't 'unavailable'
      - trigger: homeassistant
        event: start
    binary_sensor:
      - name: "Gate Garage Package Vibration Smart"
        unique_id: binary_sensor_gate_garage_package_vibration_smart
        device_class: vibration
        icon: mdi:vibrate
        # Logic: If triggered by boot, set to False. Otherwise check duration or multipath.
        state: >-
          {% if trigger.platform == 'homeassistant' %}
            false
          {% else %}
            {% set duration_sensor = 'binary_sensor.gate_garage_package_vibration_guarded' %}
            
            {# 1. Check if the 'Guarded' (long duration) sensor is already ON #}
            {% if is_state(duration_sensor, 'on') %}
              true
            {# 2. Check for rapid succession (multipath noise filter) #}
            {# If the sensor was OFF for less than 15s before turning ON, it's a double-tap. #}
            {% elif trigger.from_state is defined and 
                    (now() - trigger.from_state.last_changed).total_seconds() < 15 %}
              true
            {% else %}
              false
            {% endif %}
          {% endif %}
        auto_off: 15

  # --- Gate History (Trigger Sensors) ---
  - trigger:
      - trigger: state
        entity_id: binary_sensor.gate_garage_package_vibration_smart
        to: "on"
    sensor:
      - name: "Gate Garage Package Last Vibration Time"
        unique_id: sensor_gate_garage_package_last_vibration_time
        icon: mdi:clock-alert
        state: "{{ now().strftime('%d-%m %H:%M') }}"

  - trigger:
      - trigger: state
        entity_id: binary_sensor.door_gate_garage_contact
        to: "on"
    sensor:
      - name: "Gate Garage Package Last Opened Time"
        unique_id: sensor_gate_garage_package_last_opened_time
        icon: mdi:clock-outline
        state: "{{ now().strftime('%d-%m %H:%M') }}"

  # --- THE GATE ENTITY (The General) ---
  - cover:
      - name: "Gate Garage Package Guarded"
        unique_id: cover_gate_garage_package_guarded
        device_class: gate
        
        # State Logic: Check contact sensor
        state: >-
          {% set contact = 'binary_sensor.door_gate_garage_contact' %}
          {% if is_state(contact, 'on') %}
            open
          {% elif is_state(contact, 'off') %}
            closed
          {% else %}
            none
          {% endif %}
        
        # Availability: If Tasmota/Sensor is dead OR system is restarting, Gate is unavailable.
        availability: >-
          {{ states('switch.stove_vent_relays_gate') not in ['unavailable', 'unknown'] and 
             states('binary_sensor.door_gate_garage_contact') not in ['unavailable', 'unknown'] and
             states('sensor.restarting_status') not in ['True', 'true', 'on'] }}

        # Actions
        open_cover:
          - action: script.gate_garage_package_manager
            data:
              command: 'open'
        
        close_cover:
          - action: script.gate_garage_package_manager
            data:
              command: 'close'
        
        stop_cover:
          - action: script.gate_garage_package_manager
            data:
              command: 'toggle'

# ------------------------------------------------------------------------------
# 3. SCRIPTS (The Logic Engine)
# ------------------------------------------------------------------------------
script:
  gate_garage_package_manager:
    alias: "Gate Garage Package Manager Logic"
    icon: mdi:gate-arrow-right
    description: "Handles open/close logic with retry verification."
    fields:
      command:
        description: "The desired action: open, close, or toggle"
        example: "close"
    sequence:
      # 1. Safety Check: Restarting Status
      - if: "{{ states('sensor.restarting_status') in ['True', 'true', 'on'] }}"
        then:
          - action: persistent_notification.create
            data:
              title: "Gate Ignored"
              message: "Gate command ignored because system is restarting."
          - stop: "System is restarting."

      # 2. Clear previous error state on new command attempt
      - action: input_text.set_value
        target:
          entity_id: input_text.gate_garage_package_error_latch
        data:
          value: "None"

      - action: input_text.set_value
        target:
          entity_id: input_text.gate_garage_package_status_message
        data:
          value: "Processing {{ command }}..."

      # 3. Logic Branching
      - choose:
          # --- CASE 1: CLOSE COMMAND ---
          - conditions: "{{ command == 'close' }}"
            sequence:
              - if: "{{ is_state('binary_sensor.door_gate_garage_contact', 'off') }}"
                then:
                  - action: input_text.set_value
                    target:
                      entity_id: input_text.gate_garage_package_status_message
                    data:
                      value: "Ignored: Already Closed"
                  - stop: "Gate is already closed."
                else:
                  - action: script.gate_garage_package_actuate_and_verify
                    data:
                      target_state: 'off'
                      direction: 'close'

          # --- CASE 2: OPEN COMMAND ---
          - conditions: "{{ command == 'open' }}"
            sequence:
              - if: "{{ is_state('binary_sensor.door_gate_garage_contact', 'on') }}"
                then:
                  - action: input_text.set_value
                    target:
                      entity_id: input_text.gate_garage_package_status_message
                    data:
                      value: "Ignored: Already Open"
                  - stop: "Gate is already open."
                else:
                  - action: script.gate_garage_package_actuate_and_verify
                    data:
                      target_state: 'on'
                      direction: 'open'

          # --- CASE 3: TOGGLE COMMAND ---
          - conditions: "{{ command == 'toggle' }}"
            sequence:
              - if: "{{ is_state('binary_sensor.door_gate_garage_contact', 'off') }}"
                then:
                  # It is closed, so we Open
                  - action: script.gate_garage_package_actuate_and_verify
                    data:
                      target_state: 'on'
                      direction: 'open'
                else:
                  # It is open (or unknown), so we Close
                  - action: script.gate_garage_package_actuate_and_verify
                    data:
                      target_state: 'off'
                      direction: 'close'

  gate_garage_package_actuate_and_verify:
    alias: "Gate Garage Package Actuation Loop"
    description: "Internal script to trigger relay and verify result with retry."
    fields:
      target_state:
        description: "The binary sensor state we are looking for (on=open, off=closed)"
      direction:
        description: "Text description for logs (open/close)"
    sequence:
      # --- ATTEMPT 1 ---
      - action: input_text.set_value
        target:
          entity_id: input_text.gate_garage_package_status_message
        data:
          value: "Attempt 1: {{ direction }}ing..."
      
      - action: switch.turn_on
        target:
          entity_id: switch.stove_vent_relays_gate
      
      - wait_for_trigger:
          - trigger: state
            entity_id: binary_sensor.door_gate_garage_contact
            to: "{{ target_state }}"
        timeout: "00:00:15"
        continue_on_timeout: true
      
      # Check Success 1
      - if: "{{ is_state('binary_sensor.door_gate_garage_contact', target_state) }}"
        then:
          - action: input_text.set_value
            target:
              entity_id: input_text.gate_garage_package_status_message
            data:
              value: "Success: Gate {{ direction }}ed"
          - stop: "Success"

      # --- ATTEMPT 2 (Retry) ---
      - action: input_text.set_value
        target:
          entity_id: input_text.gate_garage_package_status_message
        data:
          value: "Retry: {{ direction }}ing..."
      
      - action: switch.turn_on
        target:
          entity_id: switch.stove_vent_relays_gate
      
      - wait_for_trigger:
          - trigger: state
            entity_id: binary_sensor.door_gate_garage_contact
            to: "{{ target_state }}"
        timeout: "00:00:15"
        continue_on_timeout: true

      # Check Success 2
      - if: "{{ is_state('binary_sensor.door_gate_garage_contact', target_state) }}"
        then:
          - action: input_text.set_value
            target:
              entity_id: input_text.gate_garage_package_status_message
            data:
              value: "Success: Gate {{ direction }}ed (Retry)"
        else:
          # --- FAILURE CONDITION ---
          - action: input_text.set_value
            target:
              entity_id: input_text.gate_garage_package_status_message
            data:
              value: "Failed"
          # Set the Error Latch for the Dashboard
          - action: input_text.set_value
            target:
              entity_id: input_text.gate_garage_package_error_latch
            data:
              value: "Error: {{ direction | title }} Failed"
          - action: persistent_notification.create
            data:
              title: "Gate Guard Error"
              message: "The gate failed to {{ direction }} after two attempts."

# ------------------------------------------------------------------------------
# 5. AUTOMATIONS (Maintenance)
# ------------------------------------------------------------------------------
automation:
  - alias: "Gate Garage Package Sensor Wake-up Monitor"
    description: "Sets error flag if sensors are stale (>24h)."
    mode: single
    triggers:
      - trigger: time_pattern
        hours: "12"
        minutes: "0"
    conditions:
      - condition: template
        value_template: >-
          {% set sensor_time = states.sensor.door_gate_garage_last_seen.state | as_timestamp(0) %}
          {{ (as_timestamp(now()) - sensor_time) > 86400 }}
    actions:
      - action: input_text.set_value
        target:
          entity_id: input_text.gate_garage_package_error_latch
        data:
          value: "Error: Sensors Stale"
      - action: persistent_notification.create
        data:
          title: "Gate Sensor Warning"
          message: "Gate sensors have not checked in for over 24 hours."
