alias: Light Control - Master Shower Occupancy
description: >-
  Version: 2.0.2. This automation provides (wasp-in-a-box inferred occupancy)
  logic. It depends on a motion sensor group, a door sensor, and a lux sensor. 
  It focuses purely on motion, door state, lux, and a timer to control the light
  and an optional exhaust fan.

  Changelog:
    - 2.0.2: Added optional exhaust fan logic tied to the door sensor.
    - 2.0.1: Added `variables` block for all key entities to simplify
      adaptation. 
    - 2.0.0: Initial creation. Forked from Main Bathroom v1.0.3. Reworked
      all logic for a "wasp-in-a-box" model.

  Key Entities Utilized:
    - Triggers/Inputs:
      - binary_sensor.master_shower_occupancy_group (Motion)
      - binary_sensor.door_master_shower_contact (Door)
      - sensor.lux_sensor_master_safe (Lux)
      - timer.master_shower_occupancy_timer (3-minute timer)
      - switch.bath_master_shower_lights (Light switch)
      - input_boolean.master_shower_occupancy_door_closed (Wasp-in-a-box boolean)
      - switch.bath_master_exhaust_fan (Optional Fan)
    - Outputs/Controlled:
      - switch.bath_master_shower_lights
      - timer.master_shower_occupancy_timer
      - input_boolean.master_shower_occupancy_door_closed
      - switch.bath_master_exhaust_fan

  ADAPTATION: To adapt this for your home, you MUST update the entity IDs in
  two places:
  1. The `triggers:` block (hardcoded entity IDs).
  2. The `variables:` block (entity IDs used by all actions).
  
variables:
  motion_sensor: binary_sensor.master_shower_occupancy_group
  door_sensor: binary_sensor.door_master_shower_contact
  lux_sensor: sensor.lux_sensor_master_safe
  light_switch: switch.bath_master_shower_lights
  occupancy_timer: timer.master_shower_occupancy_timer
  wasp_boolean: input_boolean.master_shower_occupancy_door_closed
  exhaust_fan: 'none'
  
triggers:
  - entity_id: binary_sensor.master_shower_occupancy_group
    from: "off"
    to: "on"
    id: motion_detected
    trigger: state
  - entity_id: binary_sensor.door_master_shower_contact
    from: "off"
    to: "on"
    id: door_opened
    trigger: state
  - entity_id: binary_sensor.door_master_shower_contact
    from: "on"
    to: "off"
    id: door_closed
    trigger: state
  - event_type: timer.finished
    event_data:
      entity_id: timer.master_shower_occupancy_timer
    id: timer_finished
    trigger: event
  - entity_id: switch.bath_master_shower_lights
    from: "on"
    to: "off"
    id: manual_switch_off
    trigger: state
  - entity_id: switch.bath_master_shower_lights
    from: "off"
    to: "on"
    id: manual_switch_on
    trigger: state
    
conditions: []

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: manual_switch_off
          - condition: template
            value_template: "{{ trigger.to_state.context.parent_id == none }}"
        sequence:
          - action: timer.cancel
            target:
              entity_id: "{{ occupancy_timer }}"
            data: {}
          - action: input_boolean.turn_off
            target:
              entity_id: "{{ wasp_boolean }}"
            data: {}
          - if:
              - condition: template
                value_template: "{{ exhaust_fan != 'none' }}"
            then:
              - action: switch.turn_off
                target:
                  entity_id: "{{ exhaust_fan }}"
                data: {}
          - action: system_log.write
            data:
              message: >-
                Light Control - Master Shower: Manual (UI or Physical) switch
                OFF detected. Timer and fan cancelled, wasp boolean reset.
                Light remains OFF.
              level: info
      - conditions:
          - condition: trigger
            id: manual_switch_on
          - condition: template
            value_template: "{{ trigger.to_state.context.parent_id == none }}"
        sequence:
          - action: timer.start
            target:
              entity_id: "{{ occupancy_timer }}"
            data: {}
          - action: system_log.write
            data:
              message: >-
                Light Control - Master Shower: Manual (UI or Physical) switch ON
                detected. Occupancy timer (re)started. Light remains ON.
              level: info
      - conditions:
          - condition: trigger
            id: door_opened
          - condition: template
            value_template: "{{ states(lux_sensor) | float(-1) < 1000 }}"
        sequence:
          - action: switch.turn_on
            target:
              entity_id: "{{ light_switch }}"
            data: {}
          - action: timer.start
            target:
              entity_id: "{{ occupancy_timer }}"
            data: {}
          - action: input_boolean.turn_off
            target:
              entity_id: "{{ wasp_boolean }}"
            data: {}
          - if:
              - condition: template
                value_template: "{{ exhaust_fan != 'none' }}"
            then:
              - action: switch.turn_off
                target:
                  entity_id: "{{ exhaust_fan }}"
                data: {}
          - action: system_log.write
            data:
              message: >-
                Light Control - Master Shower: Door OPENED (lux OK). Light ON,
                timer (re)started, fan OFF, and wasp boolean (inferred
                occupancy) set to FALSE.
              level: info
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: template
            value_template: "{{ states(lux_sensor) | float(-1) < 1000 }}"
        sequence:
          - action: switch.turn_on
            target:
              entity_id: "{{ light_switch }}"
            data: {}
          - action: timer.start
            target:
              entity_id: "{{ occupancy_timer }}"
            data: {}
          - action: system_log.write
            data:
              message: >-
                Light Control - Master Shower: Motion DETECTED (lux OK). Light
                ON and timer (re)started.
              level: info
          - if:
              - condition: template
                value_template: "{{ states(door_sensor) == 'off' }}"
            then:
              - action: input_boolean.turn_on
                target:
                  entity_id: "{{ wasp_boolean }}"
                data: {}
              - action: system_log.write
                data:
                  message: >-
                    Light Control - Master Shower: Motion detected while door is
                    CLOSED. Wasp boolean (inferred occupancy) set to TRUE.
                  level: info
      - conditions:
          - condition: trigger
            id: door_closed
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(light_switch, 'on') }}"
            then:
              - action: timer.start
                target:
                  entity_id: "{{ occupancy_timer }}"
                data: {}
              - action: system_log.write
                data:
                  message: >-
                    Light Control - Master Shower: Door CLOSED while light is
                    ON. Timer (re)started.
                  level: info
          - if:
              - condition: template
                value_template: "{{ exhaust_fan != 'none' }}"
            then:
              - action: switch.turn_on
                target:
                  entity_id: "{{ exhaust_fan }}"
                data: {}
              - action: system_log.write
                data:
                  message: >-
                    Light Control - Master Shower: Door CLOSED. Exhaust fan
                    TURNED ON.
                  level: info
      - conditions:
          - condition: trigger
            id: timer_finished
          - condition: template
            value_template: "{{ is_state(wasp_boolean, 'false') }}"
        sequence:
          - action: switch.turn_off
            target:
              entity_id: "{{ light_switch }}"
            data: {}
          - action: system_log.write
            data:
              message: >-
                Light Control - Master Shower: Timer FINISHED. Wasp boolean is
                'false'. Light TURNED OFF.
              level: info
    default:
      - action: system_log.write
        data:
          message: >-
            Light Control - Master Shower: Timer FINISHED, but wasp boolean is
            'true'. Light remains ON due to inferred occupancy.
          level: info
mode: restart
max_exceeded: silent
trace:
  stored_traces: 25
